project_name: awsctl
release:
  github:
    owner: outlawlabs
    name: awsctl
  draft: true
build:
  binary: awsctl
  main: ./cmd/awsctl
  flags:
    - -mod=vendor
  ldflags: -s -w -X main.timestamp={{.Date}} -X main.commitHash={{.Commit}} -X main.version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
  env:
    - CGO_ENABLED=0
archive:
  name_template: '{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}'
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
